import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import StoreProvider from "./StoreProvider";


// Load local fonts
const geistSans = localFont({
  src: "./fonts/Gilroy-Bold.ttf",
  variable: "--font-geist-sans",
});

const geistMono = localFont({
  src: "./fonts/Gilroy-Medium.ttf",
  variable: "--font-geist-mono",
  // weight: "100 900", // Optional
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
    
      <body
        className={`${geistSans.variable} ${geistMono.variable} font-sans`}
      >
       <StoreProvider>
        {children}
       </StoreProvider>
      </body>
    
    </html>
  );
}
