-- AlterTable
ALTER TABLE "Commit" ADD COLUMN     "isForce" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "isSlack" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "scheduled_time" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
